{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    {{- include "{{ .Values.app.app_name  }}.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minrplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: react-ui
  targetCPUUtilizationPercentage: {{ .Values.hpa.cuputi }}
{{- end -}}
